### PR TITLE
Scraped schedules

### PR DESCRIPTION
**Pull request by oveddan**
Scraping schedules for each day.

Providing readme for how to set the schedule for the current person.

Renamed some properties on IStudentDetails

Moved studentsData.ts to root of src

### CODE REVIEW

**Comment by EonYang** [comment]
Thank you for your work! This is more than what I expected. 
I added you as collaborator so feel free to make and changes to this repo.

**Comment by EonYang** [comment]
Remember that the other residents who're using this repo probably don't want to invest too much time learning how to use this tool. Therefore the simpler the better.

**Comment by oveddan** [comment]
Yes the idea for this branch is they are not to use the scraping tool. - they can just copy and paste their schedule for their day into their studentsData.ts  (the instruction are updated in the readme).

**Comment by t111** [comment]
Thank you~ Let's inform them.

**Pull request merged**
